ALTER TABLE traces ADD COLUMN IF NOT EXISTS input_tokens INT NOT NULL DEFAULT 0;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS output_tokens    INT NOT NULL DEFAULT 0;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS embedding_tokens INT NOT NULL DEFAULT 0;
